Currencies/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rates.urls')),
]

rates/urls.py
from django.urls import path, re_path
from .views import index, new

app_name = 'rates'
urlpatterns = [
    # Path for homepage, its avaliable just by '/'
    path('', index, name = 'index'),
    # Path for specially currency page, its avaliable by '/eur-usd', for example
    re_path(r'^(?P<currency>[a-zA-z]{2,3}-[a-zA-z]{2,3})/$', index, name = 'view'),
    path('new/', new, name ='new'),
]

rates/models.py
from django.db import models

class Rate(models.Model):
    currency = models.CharField(max_length=7)   # 'uah-usd' , 'eur-rub' etc
    rate = models.FloatField()
    date = models.DateField()                   # date of publishing

    def __str__(self):
        return "{}:{}, {}".format(self.currency, self.rate, self.date)

rates/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages

from .models import Rate


# By default we show rates for UAH-USD currency. Also we show form for adding rates for respective currency
def index(request, currency = 'uah-usd'):
    rates = Rate.objects.filter(currency = currency).order_by('date')
    return render(request, 'rates/index.html', {'rates' : rates, 'currency': currency})

# We retrieve currency from hidden value, which renders in 'index.html' by 'index' view,
# so we shouldn't demand from user to manually input this
def new(request):
    date = request.POST['date']
    rate = request.POST['rate']
    currency = request.POST['currency']
    r = Rate(rate = rate, date = date, currency = currency)
    # Handling validation errors
    try:
        r.save()
    except Exception:
        messages.error(request, 'Bad input data')
    return HttpResponseRedirect(reverse('rates:view', kwargs={'currency': currency}))

rates/templates/rates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Currency rate history</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

rates/templates/rates/index.html
{% extends 'rates/base.html' %}

{% block content %}
    <div class="container mt-2">
        <h1 class="text-primary text-center">{% filter upper %}{{currency}}{% endfilter %} rates page</h1>
        <!-- Error message in case of bad input -->
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="text-danger {{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <form action="{% url 'rates:new' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="currency" value={{currency}}>
            <div class="form-group">
                <label for="date-field">Date :</label>
                <input type="date" class="form-control" name="date" id="date-field" required>
            </div>
            <div class="form-group">
                <label for="rate-field">Rate :</label>
                <input type="number" class="form-control" name="rate" id="rate-field" step="any" required>
            </div>
            <div class="form-group">
                <input type="submit" class="form-control bg-secondary text-white" value="Add">
            </div>
        </form>
        {% if not rates %}
            <h2 class="text-primary text-center">There are no rates now</h1>
        {% else %}
            <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
            <div>
                <canvas id="RateChart"></canvas>
            </div>
            <!-- Chart.js widget -->
            <script>
            var ctx = document.getElementById('RateChart').getContext('2d');
            var chart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: [ {% for x in rates%} " {{x.date}} ", {% endfor %}],
                    datasets: [{
                        label: {% filter upper %}"{{currency}}"{% endfilter %},
                        backgroundColor: 'aqua',
                        borderColor: 'darkgrey',
                        data: [ {% for x in rates%} {{x.rate}}, {% endfor %}]
                    }]
                },
            });
            </script>
        {% endif %}
    {% endblock %}
</div>